Implement golangci linters
ONSdigital/dp-cli pull request #114
Opened 2022-02-18 16:07 UTC by RMPall

### What

- This adds the golangci linter to the dp-search-reindex-api repo. This PR enables the following linters via .golangci.yml
`
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - gocognit
    - prealloc`

This PR also attempts to fix the existing lint issues with the repo. **Please Note** in .golangci.yaml linter configuration file there is an parameter under issues attribute reffered to as `new` I have set it to false (default), but when you set it to true then it will ignore all the existing lint issues and will flag only the new lint issues. 

### How to review

Please have a look into the .golangcilint.yml file and see if the linters listed here make sense , also if you would like to add any additional linters we can always do that . For the first pass I think we have enough linters enabled (mentioned above). 

### Who can review

Anyone except me

2022-02-21 14:13 UTC, cookel2 reviewed
new lines needed at ends of some files

2022-02-21 15:08 UTC, rahulPalliyalil commented on project_generation/content/templates/event/.golangci.yml.tmpl
> +    - echo "here I can run custom commands, but no preparation needed for this repo"
Done in update1.

2022-02-21 15:08 UTC, rahulPalliyalil commented on project_generation/content/templates/base-app/.golangci.yml.tmpl
> +    - echo "here I can run custom commands, but no preparation needed for this repo"
Done in update 1.

2022-02-21 15:23 UTC, cookel2 commented
Looks good @rahulPalliyalil

2022-12-06 12:26 UTC, nshumoogum requested changes

2022-12-06 12:26 UTC, nshumoogum commented on project_generation/content/templates/api/.golangci.yml.tmpl
> +    - deadcode
I believe `deadcode` and `varcheck` have been deprecated - worth removing and checking if there are others

2022-12-06 12:26 UTC, nshumoogum commented on project_generation/content/templates/base-app/Makefile.tmpl
> +	go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
Worth updating to latest version

2023-02-24 16:08 UTC, nshumoogum commented
Closing - another PR with latest changes https://github.com/ONSdigital/dp-cli/pull/132

2023-02-24 16:08 UTC, closed without merging