update templates to generate event templates according to the new str…
ONSdigital/dp-cli pull request #70
Opened 2021-02-18 17:40 UTC by DavidSubiros

### What

- Modified templates according to the new structure of dp-hello-world for projects with kafka consumers (https://github.com/ONSdigital/dp-hello-world/pull/6)

### How to review
- Make sure template changes correspond to the dp-hello-world changes mentioned above

### Who can review

anyone

2021-02-22 08:52 UTC, CarlHembrough requested changes
I had an error when trying to generate the project: 

`panic: open /Users/carl/code/dp-cli/project_generation/content/templates/event/service/mock/kafka.go.tmpl: no such file or directory`

It seems like it's still trying to reference the kafka mock even though it's been removed?

2021-02-22 08:52 UTC, CarlHembrough commented on project_generation/content/templates/event/config/config.go.tmpl
> +	KafkaNumWorkers            int           `envconfig:"KAFKA_NUM_WORKERS"`
I think this should be added to the readme

2021-02-23 10:00 UTC, DavidSubiros commented
> I had an error when trying to generate the project:
> 
> `panic: open /Users/carl/code/dp-cli/project_generation/content/templates/event/service/mock/kafka.go.tmpl: no such file or directory`
> 
> It seems like it's still trying to reference the kafka mock even though it's been removed?

good point. Sorry I didn't spot this before.
I see that the template files are hardcoded as maps in the code. I will remove this file from the map.

2021-02-23 11:39 UTC, CarlHembrough approved these changes

2021-02-23 11:51 UTC, merged